FROM 246958245973.dkr.ecr.eu-west-2.amazonaws.com/shared-microgateway:kl-krakend-v0.0.2 as krakend

USER root

ENV REGION="global"
ENV ENVIRONMENT="landing-zone"

ENV FC_ENABLE=1
ENV FC_SETTINGS=/etc/krakend/config/settings/${ENVIRONMENT}/${REGION}
ENV FC_PARTIALS=/etc/krakend/config/partials
ENV FC_TEMPLATES=/etc/krakend/config/templates

COPY config/ /etc/krakend/config/
COPY krakend.json/ /etc/krakend/krakend.json
COPY scripts/validate.sh validate.sh

ENTRYPOINT ["sh", "./validate.sh"]